import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import ScrollContainer from "./scroll-container";
import Background from "./components/background";

import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  navigation,
}: Readonly<{
  children: React.ReactNode;
  navigation: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-screen h-screen relative">
          <Background />
          {children}
          {navigation}

          {/* <ScrollContainer>{children}</ScrollContainer> */}
        </div>
      </body>
    </html>
  );
}
